# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/ajit_120/tmp/ethernetkc/tri_mode_ethernet_mac_0_ex/imports/tri_mode_ethernet_mac_0_example_design.xdc

# XDC: /home/ajit_120/tmp/ethernetkc/tri_mode_ethernet_mac_0_ex/imports/tri_mode_ethernet_mac_0_user_phytiming.xdc

# IP: ip/tri_mode_ethernet_mac_0/tri_mode_ethernet_mac_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tri_mode_ethernet_mac_0 || ORIG_REF_NAME==tri_mode_ethernet_mac_0}]
