# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "./.Xil/Vivado-12499-ajit4-ProLiant-ML10/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7vx690tffg1761-2

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    # Skipping read_* RTL commands because this is post-elab optimize flow
    set rt::useElabCache true
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include /home/harshad/Project/git/AJIT_Ethernet/boards/v0/ip/ClkWiz156_25MHz/ClockingWizFor156_25MHz/ClockingWizFor156_25MHz.srcs/sources_1/ip/clk_wiz_1 {
      /home/harshad/Vivado/2017.1/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      /home/harshad/Vivado/2017.1/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
    }
      rt::read_verilog -include /home/harshad/Project/git/AJIT_Ethernet/boards/v0/ip/ClkWiz156_25MHz/ClockingWizFor156_25MHz/ClockingWizFor156_25MHz.srcs/sources_1/ip/clk_wiz_1 {
      ./.Xil/Vivado-12499-ajit4-ProLiant-ML10/realtime/clk_wiz_1_stub.v
      /home/harshad/Project/git/AJIT_Ethernet/boards/v0/vhdl/mac_rx_interface.v
      /home/harshad/Project/git/AJIT_Ethernet/boards/v0/vhdl/mac_tx_interface.v
      /home/harshad/Project/git/AJIT_Ethernet/boards/v0/vhdl/mac_engine.v
    }
      rt::read_vhdl -lib ahir /home/harshad/Project/git/AJIT_Ethernet/boards/v0/vhdl_libs/ahir.vhdl
      rt::read_vhdl -lib ahir_ieee_proposed /home/harshad/Project/git/AJIT_Ethernet/boards/v0/vhdl_libs/aHiR_ieee_proposed.vhdl
      rt::read_vhdl -lib simpleUartLib /home/harshad/Project/git/AJIT_Ethernet/boards/v0/vhdl_libs/simpleUartLib.vhdl
      rt::read_vhdl -lib GenericCoreAddonLib /home/harshad/Project/git/AJIT_Ethernet/boards/v0/vhdl_libs/GenericCoreAddOnLib.vhdl
      rt::read_vhdl -lib GenericGlueStuff /home/harshad/Project/git/AJIT_Ethernet/boards/v0/vhdl_libs/GenericGlueStuff.vhdl
      rt::read_vhdl -lib GlueModules /home/harshad/Project/git/AJIT_Ethernet/boards/v0/vhdl_libs/GlueModules.vhdl
      rt::read_vhdl -lib ahir_system_global_packagelib /home/harshad/Project/git/AJIT_Ethernet/boards/v0/vhdl/ahir_system_global_packagelib.vhdl
      rt::read_vhdl -lib DualClockedQueuelib /home/harshad/Project/git/AJIT_Ethernet/boards/v0/vhdl_libs/DualClockedQueuelib.vhdl
      rt::read_vhdl -lib xil_defaultlib {
      /home/harshad/Project/git/AJIT_Ethernet/boards/v0/vhdl/nic.vhdl
      /home/harshad/Project/git/AJIT_Ethernet/boards/v0/vhdl/top_level.vhdl
      /home/harshad/Project/git/AJIT_Ethernet/boards/v0/ip/FIFO_Generators/FIFO_Generators.srcs/sources_1/ip/fifo_generator_acb_req/synth/fifo_generator_acb_req.vhd
      /home/harshad/Project/git/AJIT_Ethernet/boards/v0/ip/FIFO_Generators/FIFO_Generators.srcs/sources_1/ip/fifo_generator_acb_resp/synth/fifo_generator_acb_resp.vhd
      /home/harshad/Project/git/AJIT_Ethernet/boards/v0/ip/FIFO_Generators/FIFO_Generators.srcs/sources_1/ip/fifo_generator_afb_req/synth/fifo_generator_afb_req.vhd
      /home/harshad/Project/git/AJIT_Ethernet/boards/v0/ip/FIFO_Generators/FIFO_Generators.srcs/sources_1/ip/fifo_generator_afb_resp/synth/fifo_generator_afb_resp.vhd
    }
      rt::read_vhdl -lib blk_mem_gen_v8_3_6 /home/harshad/Project/git/AJIT_Ethernet/boards/v0/ip/FIFO_Generators/FIFO_Generators.srcs/sources_1/ip/fifo_generator_acb_req/hdl/blk_mem_gen_v8_3_vhsyn_rfs.vhd
      rt::read_vhdl -lib fifo_generator_v13_1_4 /home/harshad/Project/git/AJIT_Ethernet/boards/v0/ip/FIFO_Generators/FIFO_Generators.srcs/sources_1/ip/fifo_generator_acb_req/hdl/fifo_generator_v13_1_vhsyn_rfs.vhd
      rt::read_vhdl -lib xpm /home/harshad/Vivado/2017.1/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification true
    set rt::SDCFileList ./.Xil/Vivado-12499-ajit4-ProLiant-ML10/realtime/top_level_synth.xdc
    rt::sdcChecksum
    set rt::top top_level
    set rt::reportTiming false
    rt::set_parameter elaborateOnly false
    rt::set_parameter elaborateRtl false
    rt::set_parameter eliminateRedundantBitOperator true
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter ramStyle auto
    rt::set_parameter merge_flipflops true
# MODE: 
    rt::set_parameter webTalkPath {./.Xil/Vivado-12499-ajit4-ProLiant-ML10/wt}
    rt::set_parameter enableSplitFlowPath "./.Xil/Vivado-12499-ajit4-ProLiant-ML10/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
      rt::run_synthesis -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    rt::HARTNDb_reportJobStats "Synthesis Optimization Runtime"
    rt::HARTNDb_stopSystemStats
    if { $rt::flowresult == 1 } { return -code error }

    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] && [info exists rt::doParallel] && $rt::doParallel} { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] && [info exists rt::doParallel] && $rt::doParallel} { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
