# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/harshad/Project/git/AJIT_Ethernet/10G_MAC_core/axi_10g_ethernet_0_ex/axi_10g_ethernet_0_ex.srcs/sources_1/ip/axi_10g_ethernet_0/axi_10g_ethernet_0.xci
# IP: The module: 'axi_10g_ethernet_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/harshad/Project/git/AJIT_Ethernet/10G_MAC_core/axi_10g_ethernet_0_ex/axi_10g_ethernet_0_ex.srcs/sources_1/ip/axi_10g_ethernet_0/bd_0/bd_efdb_0.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_efdb_0 || ORIG_REF_NAME==bd_efdb_0}]

# IP: /home/harshad/Project/git/AJIT_Ethernet/10G_MAC_core/axi_10g_ethernet_0_ex/axi_10g_ethernet_0_ex.srcs/sources_1/ip/axi_10g_ethernet_0/bd_0/ip/ip_0/bd_efdb_0_xmac_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_efdb_0_xmac_0 || ORIG_REF_NAME==bd_efdb_0_xmac_0}]

# IP: /home/harshad/Project/git/AJIT_Ethernet/10G_MAC_core/axi_10g_ethernet_0_ex/axi_10g_ethernet_0_ex.srcs/sources_1/ip/axi_10g_ethernet_0/bd_0/ip/ip_1/bd_efdb_0_xpcs_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_efdb_0_xpcs_0 || ORIG_REF_NAME==bd_efdb_0_xpcs_0}]

# IP: /home/harshad/Project/git/AJIT_Ethernet/10G_MAC_core/axi_10g_ethernet_0_ex/axi_10g_ethernet_0_ex.srcs/sources_1/ip/axi_10g_ethernet_0/bd_0/ip/ip_2/bd_efdb_0_dcm_locked_driver_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_efdb_0_dcm_locked_driver_0 || ORIG_REF_NAME==bd_efdb_0_dcm_locked_driver_0}]

# IP: /home/harshad/Project/git/AJIT_Ethernet/10G_MAC_core/axi_10g_ethernet_0_ex/axi_10g_ethernet_0_ex.srcs/sources_1/ip/axi_10g_ethernet_0/bd_0/ip/ip_3/bd_efdb_0_pma_pmd_type_driver_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_efdb_0_pma_pmd_type_driver_0 || ORIG_REF_NAME==bd_efdb_0_pma_pmd_type_driver_0}]

# XDC: /home/harshad/Project/git/AJIT_Ethernet/10G_MAC_core/axi_10g_ethernet_0_ex/axi_10g_ethernet_0_ex.srcs/sources_1/ip/axi_10g_ethernet_0/bd_0/bd_efdb_0_ooc.xdc

# XDC: /home/harshad/Project/git/AJIT_Ethernet/10G_MAC_core/axi_10g_ethernet_0_ex/axi_10g_ethernet_0_ex.srcs/sources_1/ip/axi_10g_ethernet_0/synth/axi_10g_ethernet_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_10g_ethernet_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# IP: /home/harshad/Project/git/AJIT_Ethernet/10G_MAC_core/axi_10g_ethernet_0_ex/axi_10g_ethernet_0_ex.srcs/sources_1/ip/axi_10g_ethernet_0/axi_10g_ethernet_0.xci
# IP: The module: 'axi_10g_ethernet_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/harshad/Project/git/AJIT_Ethernet/10G_MAC_core/axi_10g_ethernet_0_ex/axi_10g_ethernet_0_ex.srcs/sources_1/ip/axi_10g_ethernet_0/bd_0/bd_efdb_0.bd
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_efdb_0 || ORIG_REF_NAME==bd_efdb_0}]

# IP: /home/harshad/Project/git/AJIT_Ethernet/10G_MAC_core/axi_10g_ethernet_0_ex/axi_10g_ethernet_0_ex.srcs/sources_1/ip/axi_10g_ethernet_0/bd_0/ip/ip_0/bd_efdb_0_xmac_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_efdb_0_xmac_0 || ORIG_REF_NAME==bd_efdb_0_xmac_0}]

# IP: /home/harshad/Project/git/AJIT_Ethernet/10G_MAC_core/axi_10g_ethernet_0_ex/axi_10g_ethernet_0_ex.srcs/sources_1/ip/axi_10g_ethernet_0/bd_0/ip/ip_1/bd_efdb_0_xpcs_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_efdb_0_xpcs_0 || ORIG_REF_NAME==bd_efdb_0_xpcs_0}]

# IP: /home/harshad/Project/git/AJIT_Ethernet/10G_MAC_core/axi_10g_ethernet_0_ex/axi_10g_ethernet_0_ex.srcs/sources_1/ip/axi_10g_ethernet_0/bd_0/ip/ip_2/bd_efdb_0_dcm_locked_driver_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_efdb_0_dcm_locked_driver_0 || ORIG_REF_NAME==bd_efdb_0_dcm_locked_driver_0}]

# IP: /home/harshad/Project/git/AJIT_Ethernet/10G_MAC_core/axi_10g_ethernet_0_ex/axi_10g_ethernet_0_ex.srcs/sources_1/ip/axi_10g_ethernet_0/bd_0/ip/ip_3/bd_efdb_0_pma_pmd_type_driver_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_efdb_0_pma_pmd_type_driver_0 || ORIG_REF_NAME==bd_efdb_0_pma_pmd_type_driver_0}]

# XDC: /home/harshad/Project/git/AJIT_Ethernet/10G_MAC_core/axi_10g_ethernet_0_ex/axi_10g_ethernet_0_ex.srcs/sources_1/ip/axi_10g_ethernet_0/bd_0/bd_efdb_0_ooc.xdc

# XDC: /home/harshad/Project/git/AJIT_Ethernet/10G_MAC_core/axi_10g_ethernet_0_ex/axi_10g_ethernet_0_ex.srcs/sources_1/ip/axi_10g_ethernet_0/synth/axi_10g_ethernet_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_10g_ethernet_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
